### ISSUE TITLE
Fix map coloring in dark mode

### ISSUE THREAD

**Issue by thecodepapaya** [GDG-GANDHINAGAR/devfest-19-mobile#12]
The map does not look very appealing in dark mode. Use [material theme](https://material.io/design/color/dark-theme.html) guidelines for building map. Suggested by @thepushkarp 

Currently the map in dark mode looks like this.

<img src="https://user-images.githubusercontent.com/42690541/64921714-30a2c600-d7e4-11e9-8993-a26c488f7532.png" height=700>

**Comment by ashutoshsingh05** [comment]
We can take a look at these [styles](https://mapstyle.withgoogle.com/) provided by Google

|Light Theme|Dark Theme|
|---|---|
|image 1|image 2|

**Comment by thecodepapaya** [comment]
We can take a look at these [styles](https://mapstyle.withgoogle.com/) provided by Google.
What's say @pranayag @aashutoshrathi @thepushkarp  ?

|Light Themes|Dark Themes|
|---|---|
| ![flutter_01](https://user-images.githubusercontent.com/42690541/64921606-ec62f600-d7e2-11e9-9b2e-f44a1f6cf0d3.png) | ![flutter_04](https://user-images.githubusercontent.com/42690541/64921609-ecfb8c80-d7e2-11e9-8fa4-b6d76c53826f.png) |
|Standard|Dark|
| ![flutter_02](https://user-images.githubusercontent.com/42690541/64921607-ecfb8c80-d7e2-11e9-8fd0-f8399a6f4d23.png) | ![flutter_05](https://user-images.githubusercontent.com/42690541/64921610-ed942300-d7e2-11e9-97a0-901887ca68e0.png) |
|Silver|Night|
| ![flutter_03](https://user-images.githubusercontent.com/42690541/64921608-ecfb8c80-d7e2-11e9-85d6-fc829eab4f10.png) | ![flutter_06](https://user-images.githubusercontent.com/42690541/64921611-ed942300-d7e2-11e9-850e-964910de3c9b.png) |
|Retro|Aubergine|

**Comment by pranayag** [comment]
Standard and Aubergine looks good.
